using FV.Domain.Interfaces;

namespace FV.Application.Queries;
public class GenerateHeroImageQuery(ITextToImageGenService textToImageService)
{
    public async Task<string> ExecuteAsync(string prompt)
    {
        var heroPrompt = "This is a sophisticated, digitally created vector - style portrait characterized by clean, precise lines and subtle shading, reminiscent of modern digital illustration techniques. The image portrays a professional bald man with a meticulously groomed black beard and mustache, featuring crisp, sharp lines defining facial hair contours, which blend seamlessly into the smooth facial skin.  The face has clearly defined yet subtle vector shading, with smooth, gradual transitions between shadows and highlights, capturing depth without realism. The man’s eyes are rendered expressively, clearly outlined with neat lines, gently curved eyebrows above them, and subtle reflections giving a sense of life and warmth. Overall, this highly polished illustration should clearly communicate a professional yet approachable personality through its detailed and carefully stylized digital vector aesthetics. It also has a duck sitting on the bald man's shoulder. The duck is cartoonish and cute, with a bright yellow body and a cheerful expression. The background is solid black, further highlighting the subject and contributing to a dramatic contrast that emphasizes the vector-art precision and minimalistic elegance. The color palette is carefully restrained, focusing on shades of black, grey, and soft highlights to emphasize the professional and polished tone. The style balances impeccably between realistic proportions and the clean aesthetic of digital vector illustrations.";
        // var heroPrompt = "This is a sophisticated, digitally created vector - style portrait characterized by clean, precise lines and subtle shading, reminiscent of modern digital illustration techniques. There is a cute duck on his shoulder. The image portrays a professional bald man with a meticulously groomed black beard and mustache, featuring crisp, sharp lines defining facial hair contours, which blend seamlessly into the smooth facial skin.  The face has clearly defined yet subtle vector shading, with smooth, gradual transitions between shadows and highlights, capturing depth without realism. The man’s eyes are rendered expressively, clearly outlined with neat lines, gently curved eyebrows above them, and subtle reflections giving a sense of life and warmth. The lips form a calm and confident subtle smile, indicated by carefully drawn vector curves.  He wears a sleek black suit jacket over a matching black button-up shirt, both depicted with minimalistic yet clear vector shading to convey texture and fabric folds. The jacket includes subtle highlights, emphasizing the structured, elegant appearance without appearing overly realistic. The clothing details like buttons, collars, and jacket lapels are sharply defined by thin vector lines. The color palette is carefully restrained, focusing on shades of black, grey, and soft highlights to emphasize the professional and polished tone. The style balances impeccably between realistic proportions and the clean aesthetic of digital vector illustrations. The background is solid black, further highlighting the subject and contributing to a dramatic contrast that emphasizes the vector-art precision and minimalistic elegance. Overall, this highly polished illustration should clearly communicate a professional yet approachable personality through its detailed and carefully stylized digital vector aesthetics.";
        var imageBytes = await textToImageService.GenerateImageAsync(heroPrompt, prompt);
        return imageBytes;
    }
}
