name: Run Vitest Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/portfolio-react
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: |
          corepack enable
          pnpm install

      - name: ✅ Run Vitest
        run: pnpm vitest run --coverage
