packages:
  - "packages/*"
  - "frontend/portfolio-react"
  - "frontend/portfolio-opsblueprint"
  - "frontend/portfolio-busybee"
  - "frontend/portfolio-jessica"
  - "frontend/portfolio-brad"
  - "frontend/portfolio-pinchos"
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  esbuild: true
