// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TinyToes.Infrastructure;

#nullable disable

namespace TinyToes.Infrastructure.Migrations
{
    [DbContext(typeof(TinyToesDbContext))]
    [Migration("20260409012706_MultiProduct")]
    partial class MultiProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TinyToes.Infrastructure.Entities.Buyer", b =>
                {
                    b.Property<Guid>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("BuyerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("TinyToes.Infrastructure.Entities.BuyerProduct", b =>
                {
                    b.Property<Guid>("BuyerProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClaimCodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductSlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BuyerProductId");

                    b.HasIndex("ClaimCodeId");

                    b.HasIndex("BuyerId", "ProductSlug")
                        .IsUnique();

                    b.ToTable("BuyerProducts");
                });

            modelBuilder.Entity("TinyToes.Infrastructure.Entities.ClaimCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductSlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ClaimCodes");
                });

            modelBuilder.Entity("TinyToes.Infrastructure.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BundleProductSlugs")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBundle")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PriceUsd")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ProductId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TinyToes.Infrastructure.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("SessionId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TinyToes.Infrastructure.Entities.BuyerProduct", b =>
                {
                    b.HasOne("TinyToes.Infrastructure.Entities.Buyer", "Buyer")
                        .WithMany("Products")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TinyToes.Infrastructure.Entities.ClaimCode", "ClaimCode")
                        .WithMany()
                        .HasForeignKey("ClaimCodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Buyer");

                    b.Navigation("ClaimCode");
                });

            modelBuilder.Entity("TinyToes.Infrastructure.Entities.ClaimCode", b =>
                {
                    b.HasOne("TinyToes.Infrastructure.Entities.Buyer", "Buyer")
                        .WithMany("ClaimCodes")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("TinyToes.Infrastructure.Entities.Session", b =>
                {
                    b.HasOne("TinyToes.Infrastructure.Entities.Buyer", "Buyer")
                        .WithMany("Sessions")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("TinyToes.Infrastructure.Entities.Buyer", b =>
                {
                    b.Navigation("ClaimCodes");

                    b.Navigation("Products");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
