name: Run Vitest Tests (Frontend)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend/portfolio-react

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔧 Enable Corepack (for pnpm)
        run: corepack enable

      - name: 🛠 Install pnpm (if missing)
        run: corepack prepare pnpm@latest --activate

      - name: 📦 Install dependencies
        run: pnpm install

      - name: ✅ Run Vitest tests
        run: pnpm vitest run --coverage

      - name: Run project build
        run: pnpm build